name: Build & Deploy LyneApp Spring Boot Application

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    name: Build & Deploy LyneApp Spring Boot Application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 17

      - name: Build the application
        run: |
          mvn clean
          mvn -B package --file pom.xml -Dmaven.test.skip=true
